EnhancedDamage.PlayerModels =  {}
EnhancedDamage.PlayerModels["female"] = {
"models/player/group01/female_01.mdl",
"models/player/group01/female_02.mdl",
"models/player/group01/female_03.mdl",
"models/player/group01/female_04.mdl",
"models/player/group01/female_05.mdl",
"models/player/group01/female_06.mdl",
"models/player/group01/female_07.mdl",
"models/player/group03/female_01.mdl",
"models/player/group03/female_02.mdl",
"models/player/group03/female_03.mdl",
"models/player/group03/female_04.mdl",
"models/player/group03/female_05.mdl",
"models/player/group03/female_06.mdl",
"models/player/group03/female_07.mdl",
"models/player/alyx.mdl",
"models/player/mossman.mdl",
"models/Humans/alyx.mdl",
"models/Humans/mossman.mdl",
"models/mossman.mdl",
"models/alyx.mdl",
"models/Humans/Group01/Female_01.mdl",
"models/Humans/Group01/Female_02.mdl",
"models/Humans/Group01/Female_03.mdl",
"models/Humans/Group01/Female_04.mdl",
"models/Humans/Group01/Female_06.mdl",
"models/Humans/Group01/Female_07.mdl",

"models/Humans/Group02/Female_01.mdl",
"models/Humans/Group02/Female_02.mdl",
"models/Humans/Group02/Female_03.mdl",
"models/Humans/Group02/Female_04.mdl",
"models/Humans/Group02/Female_06.mdl",
"models/Humans/Group02/Female_07.mdl",

"models/Humans/Group03/Female_01.mdl",
"models/Humans/Group03/Female_02.mdl",
"models/Humans/Group03/Female_03.mdl",
"models/Humans/Group03/Female_04.mdl",
"models/Humans/Group03/Female_06.mdl",
"models/Humans/Group03/Female_07.mdl",

"models/Humans/Group03m/Female_01.mdl",
"models/Humans/Group03m/Female_02.mdl",
"models/Humans/Group03m/Female_03.mdl",
"models/Humans/Group03m/Female_04.mdl",
"models/Humans/Group03m/Female_06.mdl",
"models/Humans/Group03m/Female_07.mdl",
 }

EnhancedDamage.PlayerModels["male"] = {
"models/player/classic.mdl",
"models/player/Charple01.mdl",
"models/player/corpse1.mdl",
"models/Barney.mdl",
"models/breen.mdl",
"models/Eli.mdl",
"models/Kleiner.mdl",
"models/monk.mdl",
"models/odessa.mdl",
"models/Humans/Group01/Male_01.mdl",
"models/Humans/Group01/male_02.mdl",
"models/Humans/Group01/male_03.mdl",
"models/Humans/Group01/Male_04.mdl",
"models/Humans/Group01/Male_05.mdl",
"models/Humans/Group01/male_06.mdl",
"models/Humans/Group01/male_07.mdl",
"models/Humans/Group01/male_08.mdl",
"models/Humans/Group01/male_09.mdl",

"models/Humans/Group02/Male_01.mdl",
"models/Humans/Group02/male_02.mdl",
"models/Humans/Group02/male_03.mdl",
"models/Humans/Group02/Male_04.mdl",
"models/Humans/Group02/Male_05.mdl",
"models/Humans/Group02/male_06.mdl",
"models/Humans/Group02/male_07.mdl",
"models/Humans/Group02/male_08.mdl",
"models/Humans/Group02/male_09.mdl",

"models/Humans/Group03/Male_01.mdl",
"models/Humans/Group03/male_02.mdl",
"models/Humans/Group03/male_03.mdl",
"models/Humans/Group03/Male_04.mdl",
"models/Humans/Group03/Male_05.mdl",
"models/Humans/Group03/male_06.mdl",
"models/Humans/Group03/male_07.mdl",
"models/Humans/Group03/male_08.mdl",
"models/Humans/Group03/male_09.mdl",

"models/Humans/Group03m/Male_01.mdl",
"models/Humans/Group03m/male_02.mdl",
"models/Humans/Group03m/male_03.mdl",
"models/Humans/Group03m/Male_04.mdl",
"models/Humans/Group03m/Male_05.mdl",
"models/Humans/Group03m/male_06.mdl",
"models/Humans/Group03m/male_07.mdl",
"models/Humans/Group03m/male_08.mdl",
"models/Humans/Group03m/male_09.mdl"
}

EnhancedDamage.PlayerModels["combine"] = {
"models/player/police.mdl",
"models/player/combine_soldier.mdl",
"models/combine_super_soldier.mdl",
"models/player/combine_soldier_prisonguard.mdl",
"models/combine_soldier.mdl",
"models/combine_soldier_prisonguard.mdl",
"models/Police.mdl"
}

EnhancedDamage.PlayerModels["zombie"] = {
"models/zombie/classic.mdl",
"models/zombie/fast.mdl",
"models/zombie/fast_torso.mdl",
"models/zombie/poison.mdl",
"models/zombie/zombie_poison.mdl",
"models/player/classic.mdl",
"models/player/zombiefast.mdl",
"models/player/zombie_soldier.mdl",
"models/player/Charple01.mdl",
"models/player/corpse1.mdl",
}
